m5 = ['julaluck kongjaroon',
'Traikoon Boonnam',
'Woranasak Kaitphichetchuen',
'Nontawat Khamduang',
'Panupong Saison',
'punnagron  phungsuwan ',
'Wissarut Klinrueang',
'Amornthep Unno',
'Jakkrich testong',
'Jiratha Noisree',
'Kornpipat Leknak',
'Phattharaphon  Chomput',
'Supachai Rungsang',
'Nattapon Pluemkitmongkol',
'Pharat Dananansuk',
'Ruangwit Chokchai',
'Jirayut Buranachan ',
'Natcha Kumpa',
'Savitri  Minsaman ',
'Bannaporn Siriphan',
'Yanisa  Phaungpee ',
'Kityada Jitwimonrat',
'Sudarat Suanyim',
'Ploypraphat Pissaruk',
'Thatchanok Samai',
'Pearpilai  Boonkrong ',
'Kanyaphorn  Sittiwong ',
'Kankao Sittho',
'Kittima Kreidarporn',
'Apitsada Wachirasreesoontra',
'Sirikarn Baotun',
'Kanyawee  Udomsaree',
'Nattarinee Chimreaung',
'Pichporn Meechoksom',
'Kannisa Ratrueangudom',
'Chuda Sariphan ',
'Kanta Piyapattharakul',
'Napaspornprom Tancharakorn',
'Kingkan Roumpol',
'Wachiraya Wachiranawin']

for m5_9 in m5:
    if m5_9.strip() == "Kornpipat Leknak":
        print("<------ 11 ------>")
        continue  
    print(m5_9)  
